service: firetail-appsync-lambda

frameworkVersion: ">=2.0"

provider:
  name: aws
  region: eu-west-1
  runtime: go1.x
  environment:
    FIRETAIL_API_TOKEN: ${param:firetail-api-token}

functions:
  logs-handler:
    handler: bin/logs-handler
    timeout: 60
    events:
      - cloudwatchLog: ${param:cloudwatch-log-group}

package:
 exclude:
   - ./**
 include:
   - ./bin/**
